package webservices_lab1.J2ee.Client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import webservices_lab1.Client.PostgreSQLDAO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://webservices_lab1/")
@XmlSeeAlso({
    webservices_lab1.Client.ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<webservices_lab1.Client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://webservices_lab1/", className = "webservices_lab1.Client.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://webservices_lab1/", className = "webservices_lab1.Client.GetPersonsResponse")
    @Action(input = "http://webservices_lab1/PersonWebService/getPersonsRequest", output = "http://webservices_lab1/PersonWebService/getPersonsResponse")
    public List<webservices_lab1.Client.Person> getPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        webservices_lab1.Client.Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PostgreSQLDAO arg1);

}
